name: weather_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  get_it: 7.6.7
  provider: 6.1.1
  path_provider: 2.1.2
  hive: 2.2.3
  responsive_sizer: 3.3.0+1 
  fluttertoast: 8.2.4 
  flutter_svg: 2.0.9
  intl: 0.19.0
  geolocator: 11.0.0
  dio:
  http_parser: 4.0.2
  package_info_plus: 5.0.1
  gauge_indicator: 0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: 2.4.8
  injectable_generator: 2.4.1
  hive_generator: 2.0.1
  freezed: 2.4.6
  json_serializable: 6.7.1
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.10

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Thunder
      fonts:
        - asset: fonts/thunder/Thunder-BoldLC.ttf
          weight: 700
        - asset: fonts/thunder/Thunder-ExtraBoldLC.ttf
          weight: 800
        - asset: fonts/thunder/Thunder-BlackLC.ttf
          weight: 900
